# questions.py
import random

QUESTIONS = [
    # ========== MATHS (50 Questions) ==========
    {"q": "2 + 2 = ?", "o": ["3", "4", "5", "6"], "a": 1},
    {"q": "5 + 3 = ?", "o": ["7", "8", "9", "10"], "a": 1},
    {"q": "10 - 4 = ?", "o": ["5", "6", "7", "8"], "a": 1},
    {"q": "3 x 3 = ?", "o": ["6", "8", "9", "12"], "a": 2},
    {"q": "12 / 3 = ?", "o": ["2", "3", "4", "5"], "a": 2},
    {"q": "7 + 8 = ?", "o": ["13", "14", "15", "16"], "a": 2},
    {"q": "20 - 5 = ?", "o": ["13", "14", "15", "16"], "a": 2},
    {"q": "4 x 4 = ?", "o": ["12", "14", "15", "16"], "a": 3},
    {"q": "15 / 3 = ?", "o": ["3", "4", "5", "6"], "a": 2},
    {"q": "9 + 9 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "25 - 10 = ?", "o": ["10", "12", "14", "15"], "a": 3},
    {"q": "6 x 2 = ?", "o": ["10", "11", "12", "13"], "a": 2},
    {"q": "18 / 2 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "11 + 11 = ?", "o": ["20", "21", "22", "23"], "a": 2},
    {"q": "30 - 12 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "7 x 3 = ?", "o": ["18", "19", "20", "21"], "a": 3},
    {"q": "24 / 4 = ?", "o": ["4", "5", "6", "7"], "a": 2},
    {"q": "14 + 6 = ?", "o": ["18", "19", "20", "21"], "a": 2},
    {"q": "40 - 15 = ?", "o": ["20", "23", "24", "25"], "a": 3},
    {"q": "5 x 5 = ?", "o": ["20", "21", "24", "25"], "a": 3},
    {"q": "100 / 10 = ?", "o": ["5", "8", "10", "12"], "a": 2},
    {"q": "8 + 12 = ?", "o": ["18", "19", "20", "21"], "a": 2},
    {"q": "50 - 20 = ?", "o": ["25", "28", "30", "32"], "a": 2},
    {"q": "9 x 2 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "36 / 6 = ?", "o": ["4", "5", "6", "7"], "a": 2},
    {"q": "15 + 15 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "60 - 25 = ?", "o": ["30", "32", "35", "38"], "a": 2},
    {"q": "8 x 3 = ?", "o": ["21", "22", "23", "24"], "a": 3},
    {"q": "45 / 5 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "13 + 7 = ?", "o": ["18", "19", "20", "21"], "a": 2},
    {"q": "90 - 30 = ?", "o": ["55", "60", "65", "70"], "a": 1},
    {"q": "6 x 4 = ?", "o": ["20", "22", "24", "26"], "a": 2},
    {"q": "27 / 3 = ?", "o": ["6", "7", "8", "9"], "a": 3},
    {"q": "19 + 11 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "100 - 45 = ?", "o": ["50", "53", "55", "58"], "a": 2},
    {"q": "12 x 2 = ?", "o": ["20", "22", "24", "26"], "a": 2},
    {"q": "64 / 8 = ?", "o": ["6", "7", "8", "9"], "a": 2},
    {"q": "22 + 18 = ?", "o": ["38", "39", "40", "41"], "a": 2},
    {"q": "75 - 30 = ?", "o": ["40", "42", "45", "48"], "a": 2},
    {"q": "10 x 3 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "81 / 9 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "25 + 25 = ?", "o": ["45", "48", "50", "52"], "a": 2},
    {"q": "120 - 50 = ?", "o": ["60", "65", "70", "75"], "a": 2},
    {"q": "15 x 2 = ?", "o": ["25", "28", "30", "32"], "a": 2},
    {"q": "49 / 7 = ?", "o": ["5", "6", "7", "8"], "a": 2},
    {"q": "33 + 27 = ?", "o": ["50", "55", "58", "60"], "a": 3},
    {"q": "200 - 80 = ?", "o": ["100", "110", "115", "120"], "a": 3},
    {"q": "20 x 2 = ?", "o": ["38", "39", "40", "41"], "a": 2},
    {"q": "100 / 20 = ?", "o": ["3", "4", "5", "6"], "a": 2},
    {"q": "45 + 35 = ?", "o": ["70", "75", "80", "85"], "a": 2},
    
    # ========== ENGLISH TO HINDI (50 Questions) ==========
    {"q": "Apple ka Hindi mein kya matlab hai?", "o": ["Aam", "Seb", "Kela", "Angoor"], "a": 1},
    {"q": "Water ko Hindi mein kya kehte hain?", "o": ["Aag", "Hawa", "Pani", "Mitti"], "a": 2},
    {"q": "Sun ka Hindi mein kya matlab hai?", "o": ["Chand", "Taara", "Suraj", "Baadal"], "a": 2},
    {"q": "Mother ko Hindi mein kya kehte hain?", "o": ["Pita", "Bhai", "Maa", "Behen"], "a": 2},
    {"q": "Friend ka Hindi mein kya matlab hai?", "o": ["Dushman", "Dost", "Bhai", "Padosi"], "a": 1},
    {"q": "Happy ka Hindi mein kya matlab hai?", "o": ["Udaas", "Khush", "Gussa", "Thaka"], "a": 1},
    {"q": "Big ka Hindi mein kya matlab hai?", "o": ["Chota", "Bada", "Mota", "Patla"], "a": 1},
    {"q": "Small ka Hindi mein kya matlab hai?", "o": ["Bada", "Chota", "Lamba", "Mota"], "a": 1},
    {"q": "Fast ka Hindi mein kya matlab hai?", "o": ["Dheere", "Tez", "Aaram", "Ruk"], "a": 1},
    {"q": "Beautiful ka Hindi mein kya matlab hai?", "o": ["Sundar", "Khoobsurat", "Dono", "Koi nahi"], "a": 2},
    {"q": "Good ka Hindi mein kya matlab hai?", "o": ["Accha", "Buura", "Ganda", "Kharab"], "a": 0},
    {"q": "Bad ka Hindi mein kya matlab hai?", "o": ["Accha", "Buura", "Sundar", "Tez"], "a": 1},
    {"q": "Teacher ko Hindi mein kya kehte hain?", "o": ["Doctor", "Engineer", "Adhyapak", "Vakil"], "a": 2},
    {"q": "School ko Hindi mein kya kehte hain?", "o": ["Vidyalay", "College", "Madrasa", "Karyalay"], "a": 0},
    {"q": "Book ko Hindi mein kya kehte hain?", "o": ["Kitab", "Kagaz", "Pen", "Copy"], "a": 0},
    {"q": "Pen ko Hindi mein kya kehte hain?", "o": ["Pencil", "Kalam", "Rubber", "Scale"], "a": 1},
    {"q": "Car ko Hindi mein kya kehte hain?", "o": ["Bus", "Truck", "Bike", "Gadi"], "a": 3},
    {"q": "House ko Hindi mein kya kehte hain?", "o": ["Ghar", "Makan", "Dono", "Koi nahi"], "a": 2},
    {"q": "Dog ko Hindi mein kya kehte hain?", "o": ["Billie", "Kutta", "Sher", "Hathi"], "a": 1},
    {"q": "Cat ko Hindi mein kya kehte hain?", "o": ["Kutta", "Billie", "Chuha", "Bandar"], "a": 1},
    {"q": "Brother ko Hindi mein kya kehte hain?", "o": ["Bhai", "Behen", "Pita", "Mata"], "a": 0},
    {"q": "Sister ko Hindi mein kya kehte hain?", "o": ["Bhai", "Behen", "Maa", "Papa"], "a": 1},
    {"q": "Father ko Hindi mein kya kehte hain?", "o": ["Maa", "Bhai", "Pita", "Behen"], "a": 2},
    {"q": "Name ka Hindi mein kya matlab hai?", "o": ["Naam", "Kaam", "Ghar", "Desh"], "a": 0},
    {"q": "Work ka Hindi mein kya matlab hai?", "o": ["Aaram", "Kaam", "Khel", "Sona"], "a": 1},
    {"q": "Love ka Hindi mein kya matlab hai?", "o": ["Nafrat", "Pyar", "Gussa", "Dard"], "a": 1},
    {"q": "Hate ka Hindi mein kya matlab hai?", "o": ["Pyar", "Nafrat", "Khushi", "Accha"], "a": 1},
    {"q": "Run ka Hindi mein kya matlab hai?", "o": ["Chalna", "Daurna", "Baithna", "Sona"], "a": 1},
    {"q": "Eat ka Hindi mein kya matlab hai?", "o": ["Pina", "Khana", "Sona", "Khelna"], "a": 1},
    {"q": "Drink ka Hindi mein kya matlab hai?", "o": ["Khana", "Sona", "Pina", "Chalna"], "a": 2},
    {"q": "Sleep ka Hindi mein kya matlab hai?", "o": ["Jaagna", "Sona", "Khelna", "Parna"], "a": 1},
    {"q": "Morning ka Hindi mein kya matlab hai?", "o": ["Shaam", "Raat", "Subah", "Dopahar"], "a": 2},
    {"q": "Night ka Hindi mein kya matlab hai?", "o": ["Subah", "Shaam", "Dopahar", "Raat"], "a": 3},
    {"q": "Day ka Hindi mein kya matlab hai?", "o": ["Raat", "Din", "Shaam", "Subah"], "a": 1},
    {"q": "Week ka Hindi mein kya matlab hai?", "o": ["Mahina", "Saal", "Hafta", "Din"], "a": 2},
    {"q": "Year ka Hindi mein kya matlab hai?", "o": ["Mahina", "Saal", "Hafta", "Din"], "a": 1},
    {"q": "Month ka Hindi mein kya matlab hai?", "o": ["Saal", "Hafta", "Mahina", "Din"], "a": 2},
    {"q": "Today ka Hindi mein kya matlab hai?", "o": ["Kal", "Aaj", "Parso", "Bhokal"], "a": 1},
    {"q": "Tomorrow ka Hindi mein kya matlab hai?", "o": ["Aaj", "Kal", "Parso", "Bhokal"], "a": 1},
    {"q": "Yesterday ka Hindi mein kya matlab hai?", "o": ["Aaj", "Kal", "Parso", "Bhokal"], "a": 1},
    {"q": "Man ka Hindi mein kya matlab hai?", "o": ["Aurat", "Baccha", "Aadmi", "Budha"], "a": 2},
    {"q": "Woman ka Hindi mein kya matlab hai?", "o": ["Aadmi", "Ladka", "Aurat", "Baccha"], "a": 2},
    {"q": "Boy ka Hindi mein kya matlab hai?", "o": ["Ladki", "Aurat", "Ladka", "Aadmi"], "a": 2},
    {"q": "Girl ka Hindi mein kya matlab hai?", "o": ["Ladka", "Ladki", "Aurat", "Aadmi"], "a": 1},
    {"q": "Child ka Hindi mein kya matlab hai?", "o": ["Baccha", "Bada", "Budha", "Jawan"], "a": 0},
    
    # ========== GK & COMMON SENSE (50 Questions) ==========
    {"q": "Taj Mahal kisne banaya tha?", "o": ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], "a": 1},
    {"q": "India ka national bird kaun sa hai?", "o": ["Tota", "Mor", "Kauwa", "Chidiya"], "a": 1},
    {"q": "Ganga nadi kahan se nikalti hai?", "o": ["Mumbai", "Delhi", "Gaumukh", "Kolkata"], "a": 2},
    {"q": "Samundar ka paani kaisa hota hai?", "o": ["Meetha", "Khara", "Khatta", "Kadwa"], "a": 1},
    {"q": "Pani kis temperature par ubalta hai?", "o": ["0°C", "50°C", "100°C", "150°C"], "a": 2},
    {"q": "Pani kis temperature par jamta hai?", "o": ["0°C", "100°C", "50°C", "-10°C"], "a": 0},
    {"q": "Sher kaha rehta hai?", "o": ["Paani mein", "Aasmaan mein", "Jungle mein", "Ghar mein"], "a": 2},
    {"q": "Bill Gates kaun hai?", "o": ["Actor", "Singer", "Businessman", "Cricketer"], "a": 2},
    {"q": "Raat mein aasmaan mein kya chamakta hai?", "o": ["Suraj", "Taare", "Badal", "Hawa"], "a": 1},
    {"q": "Lal Kila kahan hai?", "o": ["Mumbai", "Kolkata", "Chennai", "Dilli"], "a": 3},
    {"q": "Mahatma Gandhi ko hum kya kehte hain?", "o": ["Chacha", "Bapu", "Netaji", "Guruji"], "a": 1},
    {"q": "Indian flag mein kitne rang hain?", "o": ["2", "3", "4", "5"], "a": 1},
    {"q": "Apple green hota hai ya red?", "o": ["Green", "Red", "Yellow", "Blue"], "a": 1},
    {"q": "Aam ka colour kya hota hai?", "o": ["Hara", "Pila", "Lal", "Narangi"], "a": 1},
    {"q": "Barish mein kya istemal karte ho?", "o": ["Cap", "Sunglass", "Chhata", "Sweater"], "a": 2},
    {"q": "Doctor kahan kaam karta hai?", "o": ["Ghar pe", "School mein", "Hospital mein", "Market mein"], "a": 2},
    {"q": "School mein padhne wali jagah?", "o": ["Playground", "Classroom", "Canteen", "Library"], "a": 1},
    {"q": "Billie ka bacha kya kehlata hai?", "o": ["Puppy", "Kitten", "Calf", "Chick"], "a": 1},
    {"q": "Kutte ka bacha kya kehlata hai?", "o": ["Kitten", "Calf", "Puppy", "Chick"], "a": 2},
    {"q": "Sher ka bacha kya kehlata hai?", "o": ["Cub", "Kitten", "Puppy", "Calf"], "a": 0},
    {"q": "Gay ka bacha kya kehlata hai?", "o": ["Puppy", "Kitten", "Calf", "Cub"], "a": 2},
    {"q": "Kela kis rang ka hota hai?", "o": ["Lal", "Hara", "Pila", "Narangi"], "a": 2},
    {"q": "Tarbooz kis rang ka hota hai?", "o": ["Andar se lal", "Andar se hara", "Andar se pila", "Andar se safed"], "a": 0},
    {"q": "Gajar ka colour kya hota hai?", "o": ["Lal ya Narangi", "Hara", "Pila", "Safed"], "a": 0},
    {"q": "Bhindi kis colour ki hoti hai?", "o": ["Lal", "Pila", "Hara", "Safed"], "a": 2},
    {"q": "Subah uthkar sabse pehle kya kehte ho?", "o": ["Good Night", "Good Morning", "Good Evening", "Hello"], "a": 1},
    {"q": "Sone se pehle kya kehte ho?", "o": ["Good Morning", "Good Evening", "Good Night", "Hello"], "a": 2},
    {"q": "Koi gift de toh kya kehte ho?", "o": ["Sorry", "Thank You", "Welcome", "Goodbye"], "a": 1},
    {"q": "Galti ho gayi toh kya kehte ho?", "o": ["Thank You", "Welcome", "Sorry", "Okay"], "a": 2},
    {"q": "Kisi se milne par kya kehte ho?", "o": ["Goodbye", "Sorry", "Thank You", "Namaste"], "a": 3},
    {"q": "Hindi diwas kab manaya jata hai?", "o": ["15 August", "26 January", "14 September", "2 October"], "a": 2},
    {"q": "Independence Day kab hai?", "o": ["15 August", "26 January", "14 September", "2 October"], "a": 0},
    {"q": "Republic Day kab hai?", "o": ["15 August", "26 January", "14 September", "2 October"], "a": 1},
    {"q": "Gandhi Jayanti kab hai?", "o": ["15 August", "26 January", "14 September", "2 October"], "a": 3},
    {"q": "Christmas kab manaya jata hai?", "o": ["25 October", "25 November", "25 December", "25 January"], "a": 2},
    {"q": "Diwali ko kya kehte hain?", "o": ["Rangon ka tyohaar", "Roshni ka tyohaar", "Khushi ka tyohaar", "Sab"], "a": 1},
    {"q": "Holi mein kya khelte hain?", "o": ["Pani", "Rang", "Gulaal", "Sab kuch"], "a": 3},
    {"q": "Sabse lamba river kaun sa hai?", "o": ["Yamuna", "Godavari", "Ganga", "Brahmaputra"], "a": 2},
    {"q": "Sabse unchai wala mountain kaun sa hai?", "o": ["K2", "Kanchenjunga", "Everest", "Makalu"], "a": 2},
    {"q": "Rashtrapati kaun hai abhi?", "o": ["Modi", "Draupadi Murmu", "Nehru", "Gandhi"], "a": 1},
    {"q": "Pradhan Mantri kaun hai abhi?", "o": ["Narendra Modi", "Rahul Gandhi", "Amit Shah", "Yogi"], "a": 0},
    {"q": "2 aur 2 milakar kya hoga?", "o": ["3", "4", "5", "6"], "a": 1},
    {"q": "5 mein se 2 kam karo?", "o": ["2", "3", "4", "5"], "a": 1},
    {"q": "10 ka half kitna hoga?", "o": ["2", "3", "4", "5"], "a": 3},
    {"q": "Pani mein kya rehta hai?", "o": ["Machli", "Sher", "Hathi", "Bandar"], "a": 0},
    {"q": "Aasmaan mein kya rehta hai?", "o": ["Paani", "Baadal", "Patthar", "Mitti"], "a": 1},
    {"q": "Subah kaun nikalta hai?", "o": ["Chand", "Suraj", "Taare", "Baadal"], "a": 1},
    {"q": "Raat mein kaun nikalta hai?", "o": ["Suraj", "Chand", "Baadal", "Hawa"], "a": 1},
    {"q": "School mein kaun padhata hai?", "o": ["Doctor", "Engineer", "Teacher", "Police"], "a": 2},
    {"q": "Bimaar hone par kahan jaate ho?", "o": ["School", "Hospital", "Market", "Ghar"], "a": 1},
]

def get_random_questions(count=30):
    return random.sample(QUESTIONS, min(count, len(QUESTIONS)))
