# questions.py

QUESTIONS = [
    # MATHS QUESTIONS
    {"q": "2 + 2 = ?", "o": ["3", "4", "5", "6"], "a": 1},
    {"q": "5 + 3 = ?", "o": ["7", "8", "9", "10"], "a": 1},
    {"q": "10 - 4 = ?", "o": ["5", "6", "7", "8"], "a": 1},
    {"q": "3 x 3 = ?", "o": ["6", "8", "9", "12"], "a": 2},
    {"q": "12 / 3 = ?", "o": ["2", "3", "4", "5"], "a": 2},
    {"q": "7 + 8 = ?", "o": ["13", "14", "15", "16"], "a": 2},
    {"q": "20 - 5 = ?", "o": ["13", "14", "15", "16"], "a": 2},
    {"q": "4 x 4 = ?", "o": ["12", "14", "15", "16"], "a": 3},
    {"q": "15 / 3 = ?", "o": ["3", "4", "5", "6"], "a": 2},
    {"q": "9 + 9 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "25 - 10 = ?", "o": ["10", "12", "14", "15"], "a": 3},
    {"q": "6 x 2 = ?", "o": ["10", "11", "12", "13"], "a": 2},
    {"q": "18 / 2 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "11 + 11 = ?", "o": ["20", "21", "22", "23"], "a": 2},
    {"q": "30 - 12 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "7 x 3 = ?", "o": ["18", "19", "20", "21"], "a": 3},
    {"q": "24 / 4 = ?", "o": ["4", "5", "6", "7"], "a": 2},
    {"q": "14 + 6 = ?", "o": ["18", "19", "20", "21"], "a": 2},
    {"q": "40 - 15 = ?", "o": ["20", "23", "24", "25"], "a": 3},
    {"q": "5 x 5 = ?", "o": ["20", "21", "24", "25"], "a": 3},
    {"q": "100 / 10 = ?", "o": ["5", "8", "10", "12"], "a": 2},
    {"q": "8 + 12 = ?", "o": ["18", "19", "20", "21"], "a": 2},
    {"q": "50 - 20 = ?", "o": ["25", "28", "30", "32"], "a": 2},
    {"q": "9 x 2 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "36 / 6 = ?", "o": ["4", "5", "6", "7"], "a": 2},
    {"q": "15 + 15 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "60 - 25 = ?", "o": ["30", "32", "35", "38"], "a": 2},
    {"q": "8 x 3 = ?", "o": ["21", "22", "23", "24"], "a": 3},
    {"q": "45 / 5 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "13 + 7 = ?", "o": ["18", "19", "20", "21"], "a": 2},
    {"q": "90 - 30 = ?", "o": ["55", "60", "65", "70"], "a": 1},
    {"q": "6 x 4 = ?", "o": ["20", "22", "24", "26"], "a": 2},
    {"q": "27 / 3 = ?", "o": ["6", "7", "8", "9"], "a": 3},
    {"q": "19 + 11 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "100 - 45 = ?", "o": ["50", "53", "55", "58"], "a": 2},
    {"q": "12 x 2 = ?", "o": ["20", "22", "24", "26"], "a": 2},
    {"q": "64 / 8 = ?", "o": ["6", "7", "8", "9"], "a": 2},
    {"q": "22 + 18 = ?", "o": ["38", "39", "40", "41"], "a": 2},
    {"q": "75 - 30 = ?", "o": ["40", "42", "45", "48"], "a": 2},
    {"q": "10 x 3 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "81 / 9 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "25 + 25 = ?", "o": ["45", "48", "50", "52"], "a": 2},
    {"q": "120 - 50 = ?", "o": ["60", "65", "70", "75"], "a": 2},
    {"q": "15 x 2 = ?", "o": ["25", "28", "30", "32"], "a": 2},
    {"q": "49 / 7 = ?", "o": ["5", "6", "7", "8"], "a": 2},
    {"q": "33 + 27 = ?", "o": ["50", "55", "58", "60"], "a": 3},
    {"q": "200 - 80 = ?", "o": ["100", "110", "115", "120"], "a": 3},
    {"q": "20 x 2 = ?", "o": ["38", "39", "40", "41"], "a": 2},
    {"q": "100 / 20 = ?", "o": ["3", "4", "5", "6"], "a": 2},
    {"q": "45 + 35 = ?", "o": ["70", "75", "80", "85"], "a": 2},
    {"q": "150 - 60 = ?", "o": ["80", "85", "90", "95"], "a": 2},
    {"q": "3 x 8 = ?", "o": ["20", "22", "24", "26"], "a": 2},
    {"q": "72 / 8 = ?", "o": ["7", "8", "9", "10"], "a": 2},
    {"q": "55 + 25 = ?", "o": ["70", "75", "80", "85"], "a": 2},
    {"q": "300 - 150 = ?", "o": ["100", "125", "150", "175"], "a": 2},
    {"q": "25 x 2 = ?", "o": ["45", "48", "50", "52"], "a": 2},
    {"q": "121 / 11 = ?", "o": ["9", "10", "11", "12"], "a": 2},
    {"q": "65 + 35 = ?", "o": ["90", "95", "100", "105"], "a": 2},
    {"q": "250 - 100 = ?", "o": ["125", "140", "150", "160"], "a": 2},
    {"q": "18 x 1 = ?", "o": ["16", "17", "18", "19"], "a": 2},
    {"q": "144 / 12 = ?", "o": ["10", "11", "12", "13"], "a": 2},
    {"q": "85 + 15 = ?", "o": ["90", "95", "100", "105"], "a": 2},
    {"q": "400 - 200 = ?", "o": ["150", "175", "200", "225"], "a": 2},
    {"q": "30 x 1 = ?", "o": ["28", "29", "30", "31"], "a": 2},
    {"q": "169 / 13 = ?", "o": ["11", "12", "13", "14"], "a": 2},
    {"q": "95 + 5 = ?", "o": ["95", "98", "99", "100"], "a": 3},
    {"q": "500 - 250 = ?", "o": ["200", "225", "250", "275"], "a": 2},
    {"q": "40 x 1 = ?", "o": ["38", "39", "40", "41"], "a": 2},
    {"q": "225 / 15 = ?", "o": ["13", "14", "15", "16"], "a": 2},

    # ENGLISH WORDS
    {"q": "What is the synonym of 'Happy'?", "o": ["Sad", "Joyful", "Angry", "Tired"], "a": 1},
    {"q": "What is the opposite of 'Big'?", "o": ["Huge", "Large", "Small", "Giant"], "a": 2},
    {"q": "What is the synonym of 'Fast'?", "o": ["Slow", "Quick", "Lazy", "Dull"], "a": 1},
    {"q": "What is the opposite of 'Hot'?", "o": ["Warm", "Cool", "Cold", "Heat"], "a": 2},
    {"q": "What is the synonym of 'Beautiful'?", "o": ["Ugly", "Pretty", "Bad", "Worst"], "a": 1},
    {"q": "What is the opposite of 'Light'?", "o": ["Bright", "Dark", "Shine", "Glow"], "a": 1},
    {"q": "What is the synonym of 'Smart'?", "o": ["Dumb", "Intelligent", "Silly", "Foolish"], "a": 1},
    {"q": "What is the opposite of 'Rich'?", "o": ["Wealthy", "Affluent", "Poor", "Luxury"], "a": 2},
    {"q": "What is the synonym of 'Quiet'?", "o": ["Loud", "Noisy", "Silent", "Chatty"], "a": 2},
    {"q": "What is the opposite of 'Strong'?", "o": ["Powerful", "Tough", "Weak", "Mighty"], "a": 2},
    {"q": "What is the synonym of 'Begin'?", "o": ["End", "Stop", "Start", "Finish"], "a": 2},
    {"q": "What is the opposite of 'Win'?", "o": ["Victory", "Success", "Lose", "Triumph"], "a": 2},
    {"q": "What is the synonym of 'Funny'?", "o": ["Serious", "Sad", "Humorous", "Boring"], "a": 2},
    {"q": "What is the opposite of 'Young'?", "o": ["New", "Fresh", "Old", "Modern"], "a": 2},
    {"q": "What is the synonym of 'Help'?", "o": ["Harm", "Assist", "Ignore", "Hurt"], "a": 1},
    {"q": "What is the opposite of 'Empty'?", "o": ["Vacant", "Full", "Hollow", "Blank"], "a": 1},
    {"q": "What is the synonym of 'Look'?", "o": ["Ignore", "Miss", "See", "Hide"], "a": 2},
    {"q": "What is the opposite of 'Soft'?", "o": ["Gentle", "Smooth", "Hard", "Light"], "a": 2},
    {"q": "What is the synonym of 'Friend'?", "o": ["Enemy", "Foe", "Buddy", "Rival"], "a": 2},
    {"q": "What is the opposite of 'Bright'?", "o": ["Shiny", "Glow", "Dull", "Light"], "a": 2},
    {"q": "What means 'To look quickly'?", "o": ["Stare", "Glance", "Gaze", "Peek"], "a": 1},
    {"q": "What means 'Very hungry'?", "o": ["Starving", "Full", "Thirsty", "Sleepy"], "a": 0},
    {"q": "What is the opposite of 'Always'?", "o": ["Forever", "Never", "Often", "Usually"], "a": 1},
    {"q": "Synonym of 'Brave'?", "o": ["Scared", "Fearful", "Courageous", "Timid"], "a": 2},
    {"q": "Opposite of 'Clean'?", "o": ["Neat", "Dirty", "Tidy", "Pure"], "a": 1},
    {"q": "Synonym of 'Easy'?", "o": ["Hard", "Difficult", "Simple", "Complex"], "a": 2},
    {"q": "Opposite of 'Thick'?", "o": ["Fat", "Wide", "Narrow", "Thin"], "a": 3},
    {"q": "Synonym of 'Angry'?", "o": ["Happy", "Calm", "Mad", "Peaceful"], "a": 2},
    {"q": "Opposite of 'Wet'?", "o": ["Moist", "Damp", "Dry", "Humid"], "a": 2},
    {"q": "Synonym of 'Pretty'?", "o": ["Ugly", "Attractive", "Plain", "Unpleasant"], "a": 1},
    {"q": "Opposite of 'Early'?", "o": ["Late", "Soon", "Prompt", "Quick"], "a": 0},
    {"q": "Synonym of 'Loud'?", "o": ["Quiet", "Silent", "Noisy", "Peaceful"], "a": 2},
    {"q": "Opposite of 'Dark'?", "o": ["Black", "Night", "Light", "Dim"], "a": 2},
    {"q": "Synonym of 'Clever'?", "o": ["Dumb", "Stupid", "Smart", "Foolish"], "a": 2},
    {"q": "Opposite of 'Near'?", "o": ["Close", "Far", "Next", "Adjacent"], "a": 1},
    {"q": "Synonym of 'Large'?", "o": ["Small", "Tiny", "Big", "Mini"], "a": 2},
    {"q": "Opposite of 'Love'?", "o": ["Like", "Care", "Hate", "Affection"], "a": 2},
    {"q": "Synonym of 'Sad'?", "o": ["Happy", "Joyful", "Unhappy", "Cheerful"], "a": 2},
    {"q": "Opposite of 'High'?", "o": ["Tall", "Low", "Elevated", "Up"], "a": 1},
    {"q": "Synonym of 'Old'?", "o": ["New", "Young", "Ancient", "Fresh"], "a": 2},
    {"q": "Opposite of 'Open'?", "o": ["Unlock", "Closed", "Shut", "Both B & C"], "a": 3},
    {"q": "Synonym of 'Nice'?", "o": ["Mean", "Rude", "Pleasant", "Unkind"], "a": 2},
    {"q": "Opposite of 'Full'?", "o": ["Complete", "Loaded", "Empty", "Total"], "a": 2},
    {"q": "Synonym of 'Talk'?", "o": ["Silent", "Mute", "Speak", "Quiet"], "a": 2},
    {"q": "Opposite of 'Deep'?", "o": ["Low", "Shallow", "Bottom", "High"], "a": 1},
    {"q": "Synonym of 'Tiny'?", "o": ["Huge", "Large", "Small", "Giant"], "a": 2},
    {"q": "Opposite of 'Slow'?", "o": ["Lazy", "Fast", "Steady", "Quiet"], "a": 1},
    {"q": "Synonym of 'Correct'?", "o": ["Wrong", "False", "Right", "Incorrect"], "a": 2},
    {"q": "Opposite of 'Top'?", "o": ["Peak", "Bottom", "Summit", "Upper"], "a": 1},
    {"q": "Synonym of 'Make'?", "o": ["Break", "Destroy", "Create", "Ruin"], "a": 2},
    {"q": "Opposite of 'Win'?", "o": ["Victory", "Lose", "Success", "Triumph"], "a": 1},
    {"q": "Synonym of 'Jump'?", "o": ["Sit", "Stand", "Leap", "Stop"], "a": 2},
    {"q": "Opposite of 'Day'?", "o": ["Sun", "Morning", "Night", "Evening"], "a": 2},
    {"q": "Synonym of 'Cry'?", "o": ["Laugh", "Weep", "Smile", "Grin"], "a": 1},
    {"q": "Opposite of 'Male'?", "o": ["Man", "Boy", "Female", "Gentleman"], "a": 2},
    {"q": "Synonym of 'Run'?", "o": ["Walk", "Sprint", "Crawl", "Stand"], "a": 1},
    {"q": "Opposite of 'Life'?", "o": ["Alive", "Living", "Death", "Breathing"], "a": 2},
    {"q": "Synonym of 'Gift'?", "o": ["Curse", "Present", "Loss", "Penalty"], "a": 1},
    {"q": "Opposite of 'Yes'?", "o": ["Yeah", "Sure", "No", "Okay"], "a": 2},
    {"q": "Synonym of 'Good'?", "o": ["Bad", "Poor", "Excellent", "Terrible"], "a": 2},
    {"q": "Opposite of 'True'?", "o": ["Real", "Actual", "False", "Correct"], "a": 2},
    {"q": "Synonym of 'Big'?", "o": ["Small", "Little", "Large", "Tiny"], "a": 2},
    {"q": "Opposite of 'Inside'?", "o": ["Inner", "Outside", "Internal", "Within"], "a": 1},
    {"q": "Synonym of 'Push'?", "o": ["Pull", "Shove", "Drag", "Tug"], "a": 1},
    {"q": "Opposite of 'Forward'?", "o": ["Front", "Ahead", "Backward", "Advance"], "a": 2},
    {"q": "Synonym of 'Sleep'?", "o": ["Wake", "Rest", "Active", "Awake"], "a": 1},
    {"q": "Opposite of 'Add'?", "o": ["Plus", "Total", "Subtract", "Sum"], "a": 2},
    {"q": "Synonym of 'Old'?", "o": ["Aged", "New", "Young", "Fresh"], "a": 0},
    {"q": "Opposite of 'Above'?", "o": ["Over", "Below", "Up", "Top"], "a": 1},

    # GK QUESTIONS
    {"q": "What is the capital of India?", "o": ["Mumbai", "Delhi", "Kolkata", "Chennai"], "a": 1},
    {"q": "Who is known as Father of India?", "o": ["Nehru", "Gandhi", "Patel", "Tilak"], "a": 1},
    {"q": "How many days in a week?", "o": ["5", "6", "7", "8"], "a": 2},
    {"q": "What is the color of the sky?", "o": ["Green", "Red", "Blue", "Yellow"], "a": 2},
    {"q": "Which animal is known as 'Ship of Desert'?", "o": ["Horse", "Elephant", "Camel", "Lion"], "a": 2},
    {"q": "How many months in a year?", "o": ["10", "11", "12", "13"], "a": 2},
    {"q": "What is the national bird of India?", "o": ["Eagle", "Peacock", "Sparrow", "Crow"], "a": 1},
    {"q": "Which is the longest river in India?", "o": ["Yamuna", "Godavari", "Ganga", "Brahmaputra"], "a": 2},
    {"q": "What is the national flower of India?", "o": ["Rose", "Marigold", "Lotus", "Sunflower"], "a": 2},
    {"q": "Which is the largest continent?", "o": ["Africa", "Asia", "Europe", "Australia"], "a": 1},
    {"q": "How many colors in a rainbow?", "o": ["5", "6", "7", "8"], "a": 2},
    {"q": "Which is the fastest animal?", "o": ["Lion", "Tiger", "Cheetah", "Leopard"], "a": 2},
    {"q": "What is the national anthem of India?", "o": ["Vande Mataram", "Jana Gana Mana", "Sare Jahan Se Achha", "Mere Desh Ki Dharti"], "a": 1},
    {"q": "Who wrote the national anthem?", "o": ["Sarojini Naidu", "Bankim Chandra", "Rabindranath Tagore", "Muhammad Iqbal"], "a": 2},
    {"q": "Which planet is known as Red Planet?", "o": ["Jupiter", "Mars", "Venus", "Saturn"], "a": 1},
    {"q": "Which is the smallest continent?", "o": ["Europe", "Antarctica", "Australia", "South America"], "a": 2},
    {"q": "What is the currency of India?", "o": ["Dollar", "Rupee", "Euro", "Pound"], "a": 1},
    {"q": "Which festival is called 'Festival of Lights'?", "o": ["Holi", "Eid", "Diwali", "Christmas"], "a": 2},
    {"q": "Who painted the Mona Lisa?", "o": ["Van Gogh", "Picasso", "Da Vinci", "Rembrandt"], "a": 2},
    {"q": "Which is the tallest mountain in the world?", "o": ["K2", "Kanchenjunga", "Everest", "Makalu"], "a": 2},
    {"q": "How many letters in English alphabet?", "o": ["24", "25", "26", "27"], "a": 2},
    {"q": "What is the national sport of India?", "o": ["Cricket", "Hockey", "Football", "Kabaddi"], "a": 1},
    {"q": "Which is the largest ocean?", "o": ["Atlantic", "Indian", "Pacific", "Arctic"], "a": 2},
    {"q": "Who invented the light bulb?", "o": ["Newton", "Einstein", "Edison", "Galileo"], "a": 2},
    {"q": "Which is the national animal of India?", "o": ["Elephant", "Lion", "Tiger", "Peacock"], "a": 2},
    {"q": "What is the square root of 64?", "o": ["6", "7", "8", "9"], "a": 2},
    {"q": "Which is the coldest place on Earth?", "o": ["Greenland", "Antarctica", "Siberia", "Canada"], "a": 1},
    {"q": "Who is the first man on the moon?", "o": ["Neil Armstrong", "Buzz Aldrin", "Michael Collins", "Yuri Gagarin"], "a": 0},
    {"q": "Which is the largest country by area?", "o": ["Canada", "China", "USA", "Russia"], "a": 3},
    {"q": "What is the national language of Pakistan?", "o": ["Punjabi", "Sindhi", "Urdu", "Pashto"], "a": 2},
    {"q": "Which is the longest wall in the world?", "o": ["Hadrian's Wall", "Great Wall of China", "Berlin Wall", "Wall of Jericho"], "a": 1},
    {"q": "Who wrote Romeo and Juliet?", "o": ["Charles Dickens", "Jane Austen", "William Shakespeare", "Mark Twain"], "a": 2},
    {"q": "What is the national game of Japan?", "o": ["Baseball", "Sumo", "Karate", "Judo"], "a": 1},
    {"q": "Which is the largest desert?", "o": ["Gobi", "Sahara", "Kalahari", "Atacama"], "a": 1},
    {"q": "Who discovered gravity?", "o": ["Einstein", "Newton", "Galileo", "Archimedes"], "a": 1},
    {"q": "What is the boiling point of water?", "o": ["90°C", "95°C", "100°C", "105°C"], "a": 2},
    {"q": "Which is the smallest country?", "o": ["Monaco", "San Marino", "Vatican City", "Malta"], "a": 2},
    {"q": "Who is the CEO of Tesla?", "o": ["Jeff Bezos", "Bill Gates", "Elon Musk", "Mark Zuckerberg"], "a": 2},
    {"q": "What is the chemical symbol for Gold?", "o": ["Go", "Gd", "Au", "Ag"], "a": 2},
    {"q": "Which is the most populated country?", "o": ["India", "USA", "China", "Indonesia"], "a": 2},
    {"q": "What is the national fruit of India?", "o": ["Apple", "Banana", "Mango", "Orange"], "a": 2},
    {"q": "Who is the founder of Microsoft?", "o": ["Steve Jobs", "Bill Gates", "Larry Page", "Mark Zuckerberg"], "a": 1},
    {"q": "Which is the largest bone in human body?", "o": ["Skull", "Spine", "Femur", "Rib"], "a": 2},
    {"q": "What is the fastest bird?", "o": ["Eagle", "Falcon", "Hawk", "Vulture"], "a": 1},
    {"q": "Which country gave the world 'Yoga'?", "o": ["China", "Japan", "India", "Nepal"], "a": 2},
    {"q": "What is the capital of France?", "o": ["London", "Berlin", "Paris", "Madrid"], "a": 2},
    {"q": "Who is known as 'King of Pop'?", "o": ["Elvis Presley", "Michael Jackson", "Prince", "Madonna"], "a": 1},
    {"q": "Which is the largest island?", "o": ["Australia", "Greenland", "New Guinea", "Madagascar"], "a": 1},
    {"q": "What is the national tree of India?", "o": ["Neem", "Peepal", "Banyan", "Mango"], "a": 2},
    {"q": "Who wrote the Indian national anthem?", "o": ["Bankim Chandra", "Rabindranath Tagore", "Sarojini Naidu", "Muhammad Iqbal"], "a": 1},
    {"q": "Which is the most spoken language in the world?", "o": ["English", "Hindi", "Mandarin", "Spanish"], "a": 2},
    {"q": "What is the freezing point of water?", "o": ["-1°C", "0°C", "1°C", "2°C"], "a": 1},
]

def get_random_questions(count=15):
    import random
    return random.sample(QUESTIONS, min(count, len(QUESTIONS)))
